export type AboutPageData = {
app_name: string;
current_locale: string;
languages: Array<LanguageOptionData>;
title: string;
subtitle: string;
eyebrow: string;
hero_badge: string;
filter_watch_label: string;
visual_label: string;
pipeline_label: string;
faq_title: string;
faq_subtitle: string;
closing_label: string;
intro: Array<any>;
stats: Array<any>;
sections: Array<any>;
timeline: Array<any>;
faq: Array<any>;
closing_title: string;
closing_body: string;
};
export type AgentPromptData = {
message: string;
};
export type BaseLimitType = 'fixed' | 'unlimited' | 'none';
export type CountdownDetailData = {
id: number;
slug: string;
title: string;
summary: string;
description: string;
image_url: string;
severity: string;
timer: CountdownTimerData;
main_projection: ProjectionData | null;
causes: Array<any>;
consequences: Array<any>;
recommended_actions: Array<any>;
projections: Array<ProjectionData>;
visualizations: Array<VisualizationData>;
news: Array<NewsData>;
};
export type CountdownForecastsData = {
countdown_slug: string;
projections: Array<ProjectionData>;
projection_chart: VisualizationData | null;
};
export type CountdownIndexData = {
id: number;
slug: string;
title: string;
summary: string;
image_url: string;
status: string;
severity: string;
sort_order: number;
timer: CountdownTimerData;
main_projection: ProjectionData | null;
url: string;
is_selected: boolean;
};
export type CountdownInitiativesSectionData = {
countdown_slug: string;
initiatives: Array<InitiativeData>;
};
export type CountdownNewsSectionData = {
countdown_slug: string;
news: Array<NewsData>;
};
export type CountdownOverviewData = {
id: number;
slug: string;
title: string;
summary: string;
description: string;
image_url: string;
severity: string;
timer: CountdownTimerData;
main_projection: ProjectionData | null;
causes: Array<any>;
consequences: Array<any>;
recommended_actions: Array<any>;
key_indicators: VisualizationData | null;
};
export type CountdownPageData = {
app_name: string;
current_locale: string;
languages: Array<LanguageOptionData>;
hero: Array<any>;
countdowns: Array<CountdownIndexData>;
sidebar: HomeSidebarData;
selected_countdown: CountdownOverviewData | null;
};
export type CountdownSeverity = 'low' | 'moderate' | 'elevated' | 'high' | 'severe' | 'critical' | 'existential';
export type CountdownStatisticsData = {
countdown_slug: string;
visualizations: Array<VisualizationData>;
};
export type CountdownStatus = 'draft' | 'monitoring' | 'active' | 'stabilized' | 'averted' | 'occurred' | 'archived';
export type CountdownTimerData = {
target_date: string | null;
estimated_label: string;
is_elapsed: boolean;
};
export type FreeLimitType = 'daily' | 'monthly' | 'none';
export type HomeSidebarData = {
latest_news: Array<LatestNewsItemData>;
signal_activity: NewsActivityData;
};
export type InitiativeData = {
locale: string;
type: string;
title: string;
excerpt: string;
body: string | null;
organization: string | null;
url: string;
content_type: string;
image_url: string;
embed_url: string | null;
external_provider: string | null;
cta_label: string | null;
starts_at: string | null;
ends_at: string | null;
is_featured: boolean;
sort_order: number;
};
export type InitiativeLocale = 'all' | 'en' | 'it' | 'fr' | 'de' | 'es' | 'nl' | 'sv' | 'pl';
export type InitiativeType = 'petition' | 'protest' | 'fundraiser' | 'campaign' | 'resource' | 'other';
export type LanguageOptionData = {
code: string;
label: string;
native_label: string;
flag: string;
url: string;
is_current: boolean;
};
export type LatestNewsItemData = {
id: number;
title: string;
excerpt: string;
content_type: string;
source_name: string | null;
source_url: string | null;
image_url: string;
published_at: string;
countdown_slug: string;
countdown_title: string;
countdown_url: string;
};
export type LoginData = {
email: string;
password: string;
};
export type NewsActivityData = {
window_start: string;
window_end: string;
bucket_labels: Array<any>;
bucket_counts: Array<any>;
total_items: number;
unique_sources: number;
latest_published_at: string | null;
top_countdown_slug: string | null;
top_countdown_title: string | null;
top_countdown_count: number;
};
export type NewsData = {
locale: string;
title: string;
excerpt: string;
content_type: string;
source_name: string | null;
source_url: string | null;
image_url: string;
embed_url: string | null;
external_provider: string | null;
published_at: string | null;
is_featured: boolean;
};
export type NewsLocale = 'all' | 'en' | 'it' | 'fr' | 'de' | 'es' | 'nl' | 'sv' | 'pl';
export type ProjectionData = {
type: string;
target_date: string | null;
title: string;
summary: string;
confidence_score: number;
probability_score: number;
trend: string;
visualizations: Array<VisualizationData>;
};
export type ProjectionType = 'optimistic' | 'neutral' | 'pessimistic' | 'other';
export type RotableKeyData = {
service: string | null;
key: string | null;
base_limit_type: string;
max_base_usage: number | null;
current_base_usage: number;
free_limit_type: string;
max_free_usage: number | null;
current_free_usage: number;
free_usage_resets_at: any | null;
reset_timezone: string;
extra_data: Array<any> | null;
is_active: boolean;
is_depleted: boolean;
depleted_at: string | null;
created_at: string | null;
updated_at: string | null;
last_used_at: string | null;
};
export type SaveCountdownData = {
slug: string;
title: Array<any>;
summary: Array<any>;
description: Array<any> | null;
causes: Array<any> | null;
consequences: Array<any> | null;
recommended_actions: Array<any> | null;
severity: string;
status: string;
target_date: string | null;
image_path: string;
accent_color: string;
sort_order: number;
is_published: boolean;
};
export type SaveInitiativeData = {
locale: string;
type: string;
title: string;
excerpt: string;
body: string | null;
organization: string | null;
url: string;
image_path: string | null;
cta_label: string | null;
starts_at: string | null;
ends_at: string | null;
sort_order: number;
is_featured: boolean;
content_type: string | null;
preview_image_url: string | null;
embed_url: string | null;
external_provider: string | null;
external_id: string | null;
};
export type SaveNewsData = {
locale: string;
title: string;
excerpt: string;
source_name: string | null;
source_url: string | null;
image_path: string | null;
published_at: string | null;
sort_order: number;
is_featured: boolean;
content_type: string | null;
preview_image_url: string | null;
embed_url: string | null;
external_provider: string | null;
external_id: string | null;
};
export type SaveOpenAiKeyData = {
label: string | null;
key: string | null;
base_limit_type: string;
max_base_usage: number | null;
free_limit_type: string;
max_free_usage: number | null;
is_active: boolean;
};
export type SaveProjectionData = {
type: string;
target_date: string | null;
title: Array<any>;
summary: Array<any> | null;
confidence_score: number;
probability_score: number;
trend: string;
methodology: Array<any> | null;
sort_order: number;
};
export type SaveUserData = {
name: string;
email: string;
password: string | null;
};
export type SaveVisualizationData = {
key: string;
type: string;
title: Array<any>;
description: Array<any> | null;
sources: Array<any>;
reasoning: Array<any>;
payload: Array<any>;
schema_version: number;
sort_order: number;
};
export type SeoAlternateData = {
hreflang: string;
url: string;
};
export type SeoImageData = {
url: string;
width: number | null;
height: number | null;
alt: string;
};
export type SeoOpenGraphData = {
title: string;
description: string;
url: string;
type: string;
site_name: string;
locale: string;
alternate_locales: Array<any>;
image: SeoImageData;
};
export type SeoPageData = {
title: string;
description: string;
canonical_url: string;
robots: string;
locale: string;
alternates: Array<SeoAlternateData>;
x_default_url: string;
open_graph: SeoOpenGraphData;
twitter: SeoTwitterData;
date_modified: string | null;
structured_data: Array<any>;
};
export type SeoTwitterData = {
card: string;
title: string;
description: string;
image_url: string;
image_alt: string;
};
export type VisualizationData = {
key: string;
type: string;
title: string;
description: string | null;
sources: Array<any>;
reasoning: string;
payload: Array<any>;
schema_version: number;
sort_order: number;
};
export type VisualizationType = 'line' | 'area' | 'bar' | 'sparkline' | 'kpi' | 'timeline' | 'risk_matrix' | 'custom';
