<?php

declare(strict_types=1);

return [
    'expected_origin' => 'https://doomsday-clock.com',
    'cache_prefix_required_fragment' => 'production',

    'artifacts' => [
        'manifests' => [
            'Client Vite manifest' => [
                'path' => public_path('build/manifest.json'),
                'json' => true,
            ],
            'SSR manifest' => [
                'path' => base_path('bootstrap/ssr/ssr-manifest.json'),
                'json' => true,
            ],
            'SSR bundle' => [
                'path' => base_path('bootstrap/ssr/ssr.js'),
                'json' => false,
            ],
            'Official Discord icon' => [
                'path' => public_path('images/community/discord.png'),
                'json' => false,
            ],
            'Official Telegram icon' => [
                'path' => public_path('images/community/telegram.png'),
                'json' => false,
            ],
        ],
        'approved_runtime_sources' => [
            'Community links component' => [
                'path' => resource_path('js/Components/Doomsday/CommunityLinks.vue'),
                'markers' => [
                    "readonly placement?: 'header' | 'about';",
                    'https://discord.gg/NmKXDzwzK',
                    'https://t.me/doomsdayclockofficial',
                    "iconSrc: '/images/community/discord.png'",
                    "iconSrc: '/images/community/telegram.png'",
                    'rel="noopener noreferrer"',
                    'h-9 w-9',
                    'v-if="!isHeader"',
                ],
            ],
            'Site header community integration' => [
                'path' => resource_path('js/Components/Doomsday/SiteHeader.vue'),
                'markers' => [
                    "import CommunityLinks from './CommunityLinks.vue';",
                    '<CommunityLinks placement="header" />',
                    '<nav class=',
                ],
            ],
            'About closing-band integration' => [
                'path' => resource_path('js/Components/Doomsday/AboutClosingBand.vue'),
                'markers' => [
                    "import CommunityLinks from './CommunityLinks.vue';",
                    '<PatreonSupportLink placement="about" />',
                    '<CommunityLinks />',
                ],
            ],
        ],
        'generated' => [
            'Generated TypeScript DTOs' => [
                'path' => resource_path('js/types/generated.d.ts'),
                'markers' => [
                    'export type CountdownPageData = {',
                    'sidebar: HomeSidebarData;',
                ],
            ],
            'Generated form rules' => [
                'path' => resource_path('js/generated/form-rules.ts'),
                'markers' => [
                    'AUTO-GENERATED by form-bridge:generate',
                    'export const SaveCountdownDataRules',
                ],
            ],
            'Generated validation messages' => [
                'path' => resource_path('js/generated/validation-messages.ts'),
                'markers' => [
                    'AUTO-GENERATED by form-bridge:generate',
                    'export const validationMessages',
                ],
            ],
        ],
    ],

    'release_exclusions' => [
        'paths' => [
            base_path('.env'),
            base_path('.env.backup'),
            base_path('.env.prod'),
            base_path('.env.production'),
            base_path('.phpunit.result.cache'),
            base_path('.agent'),
            base_path('.artifacts'),
            base_path('.codegraph'),
            base_path('.omo'),
            base_path('.opencode'),
            base_path('.playwright-mcp'),
            base_path('node_modules'),
            base_path('tests'),
            base_path('z-docs'),
            public_path('hot'),
            storage_path('pail'),
        ],
        'bytecode_roots' => [
            base_path('app'),
            base_path('bootstrap'),
            base_path('config'),
            base_path('database'),
            base_path('public'),
            base_path('resources'),
            base_path('routes'),
            base_path('scripts'),
        ],
        'local_key_patterns' => [
            storage_path('*.key'),
            storage_path('*.pem'),
            storage_path('*.p12'),
        ],
        'dev_packages' => [
            'fakerphp/faker',
            'laravel/pail',
            'laravel/pao',
            'laravel/pint',
            'mockery/mockery',
            'nunomaduro/collision',
            'phpunit/phpunit',
            'simone-bianco/vue-ui-components-testing',
            'spatie/laravel-typescript-transformer',
        ],
    ],

    'route_deny_markers' => [
        'agent/demo',
        'agent.demo',
        'api/file-upload/upload',
        'file-upload.upload',
        'api/select-demo',
        'select-demo.',
        'test-components',
        '_ignition',
        'debugbar',
        'horizon',
        'pao',
        'pulse',
        'telescope',
        'testbench',
    ],

    'backup' => [
        'required_package' => 'spatie/laravel-backup',
        'expected_time' => '03:00',
        'expected_timezone' => 'Europe/Rome',
        'local_only_disks' => ['local', 'public', 'backup'],
        'require_non_windows_server' => true,
    ],

    'analytics' => [
        'google_tag_manager_id' => env('VITE_GOOGLE_TAG_MANAGER_ID', ''),
        'google_analytics_id' => env('VITE_GOOGLE_ANALYTICS_ID', ''),
        'legal_facts' => [
            'controller' => env('PRODUCTION_LEGAL_CONTROLLER', '[DA VERIFICARE]'),
            'contact' => env('PRODUCTION_PRIVACY_CONTACT', '[DA VERIFICARE]'),
            'vendor' => env('PRODUCTION_ANALYTICS_VENDOR', '[DA VERIFICARE]'),
            'retention' => env('PRODUCTION_ANALYTICS_RETENTION', '[DA VERIFICARE]'),
        ],
        'placeholder_markers' => [
            '[da verificare]',
            'example.com',
            'placeholder',
            'tbd',
            'todo',
        ],
        'legal_policy_path' => resource_path('js/Pages/Doomsday/LegalPolicy.vue'),
        'legal_policy_placeholder_markers' => [
            'final privacy contact details must be completed by the controller before production launch',
            'details must be updated when real service ids are added',
            'i contatti privacy definitivi devono essere completati dal titolare prima della pubblicazione in produzione',
            'i dettagli vanno aggiornati quando vengono inseriti gli id reali dei servizi',
        ],
    ],
];
