<?php

declare(strict_types=1);

return [
    'demo_agent' => [
        'enabled' => (bool) env('DEMO_AGENT_ENABLED', true),
        'environments' => ['local', 'testing'],
    ],

    'login' => [
        'max_attempts_per_minute' => (int) env('LOGIN_RATE_LIMIT_MAX_ATTEMPTS', 5),
    ],

    'headers' => [
        'enabled' => (bool) env('SECURITY_HEADERS_ENABLED', true),
        'x_content_type_options' => 'nosniff',
        'referrer_policy' => 'strict-origin-when-cross-origin',
        'permissions_policy' => 'camera=(), geolocation=(), microphone=(), payment=(), usb=()',
        'frame_options' => 'DENY',
    ],

    'csp' => [
        'enabled' => (bool) env('SECURITY_CSP_REPORT_ONLY_ENABLED', true),
        'report_only' => true,
        'directives' => [
            'default-src' => ["'self'"],
            'base-uri' => ["'self'"],
            'object-src' => ["'none'"],
            'frame-ancestors' => ["'none'"],
            'form-action' => ["'self'"],
            'script-src' => ["'self'", "'unsafe-inline'", 'https://www.googletagmanager.com'],
            'style-src' => ["'self'", "'unsafe-inline'"],
            'font-src' => ["'self'", 'data:'],
            'connect-src' => [
                "'self'",
                'https://www.google-analytics.com',
                'https://region1.google-analytics.com',
                'https://analytics.google.com',
                'https://stats.g.doubleclick.net',
            ],
            'frame-src' => [
                "'self'",
                'https://www.youtube.com',
                'https://www.youtube-nocookie.com',
            ],
            'img-src' => [
                "'self'",
                'data:',
                'blob:',
                'https://cdn.who.int',
                'https://climate-adapt.eea.europa.eu',
                'https://climate.copernicus.eu',
                'https://commission.europa.eu',
                'https://csis-website-prod.s3.amazonaws.com',
                'https://defence-industry-space.ec.europa.eu',
                'https://digital-skills-jobs.europa.eu',
                'https://digital-strategy.ec.europa.eu',
                'https://ec.europa.eu',
                'https://eda.europa.eu',
                'https://employment-social-affairs.ec.europa.eu',
                'https://gardp.org',
                'https://heathealth.info',
                'https://i.ytimg.com',
                'https://iris.who.int',
                'https://media.tghn.org',
                'https://medicalcountermeasures.gov',
                'https://mission-adaptation-portal.ec.europa.eu',
                'https://mptf.undp.org',
                'https://pact-for-skills.ec.europa.eu',
                'https://s7g10.scene7.com',
                'https://upload.wikimedia.org',
                'https://wmo.int',
                'https://www.amrleaders.org',
                'https://www.ecdc.europa.eu',
                'https://www.ema.europa.eu',
                'https://www.ilo.org',
                'https://www.un.org',
            ],
            'media-src' => ["'self'"],
            'worker-src' => ["'self'", 'blob:'],
            'manifest-src' => ["'self'"],
        ],
    ],

    'hsts' => [
        'enabled' => (bool) env('SECURITY_HSTS_ENABLED', false),
        'https_and_subdomains_proven' => (bool) env('SECURITY_HSTS_PROOF_CONFIRMED', false),
        'max_age' => (int) env('SECURITY_HSTS_MAX_AGE', 31536000),
        'include_subdomains' => false,
        'preload' => false,
    ],

    'routes' => [
        'public_indexable' => [
            'home',
            'about',
            'countdowns.show',
        ],
        'public_discovery' => [
            'sitemap',
            'robots',
        ],
        'public_noindex' => [
            'privacy',
            'cookie-policy',
            'countdowns.data.overview',
            'countdowns.data.forecasts',
            'countdowns.data.statistics',
            'countdowns.data.news',
            'countdowns.data.initiatives',
            'login',
            'login.store',
            'logout',
        ],
        'admin_private' => [
            'backoffice.index',
            'backoffice.countdowns.index',
            'backoffice.countdowns.create',
            'backoffice.countdowns.store',
            'backoffice.countdowns.edit',
            'backoffice.countdowns.update',
            'backoffice.countdowns.destroy',
            'backoffice.countdowns.projections.create',
            'backoffice.countdowns.projections.edit',
            'backoffice.countdowns.projections.store',
            'backoffice.countdowns.projections.update',
            'backoffice.countdowns.projections.destroy',
            'backoffice.countdowns.visualizations.create',
            'backoffice.countdowns.visualizations.edit',
            'backoffice.countdowns.visualizations.store',
            'backoffice.countdowns.visualizations.update',
            'backoffice.countdowns.visualizations.destroy',
            'backoffice.countdowns.projections.visualizations.create',
            'backoffice.countdowns.projections.visualizations.edit',
            'backoffice.countdowns.projections.visualizations.store',
            'backoffice.countdowns.projections.visualizations.update',
            'backoffice.countdowns.projections.visualizations.destroy',
            'backoffice.countdowns.news.store',
            'backoffice.countdowns.news.update',
            'backoffice.countdowns.news.destroy',
            'backoffice.countdowns.initiatives.store',
            'backoffice.countdowns.initiatives.update',
            'backoffice.countdowns.initiatives.destroy',
            'backoffice.users.index',
            'backoffice.users.store',
            'backoffice.users.update',
            'backoffice.users.destroy',
            'backoffice.openai-keys.index',
            'backoffice.openai-keys.store',
            'backoffice.openai-keys.update',
            'backoffice.openai-keys.destroy',
        ],
        'local_only' => [
            'agent.demo',
        ],
    ],
];
