<?php

declare(strict_types=1);

use App\Enums\VisualizationType;

$shared = require __DIR__.'/../_shared.php';

return new class($shared)
{
    public function __construct(private object $shared) {}

    /** @return array<string, mixed> */
    public function projectionCurveVisualization(): array
    {
        return $this->shared->chartVisualization(
            key: 'projection_curve',
            type: VisualizationType::Line,
            title: $this->shared->t(en: 'Conditional security-window pressure', it: 'Pressione della finestra di sicurezza condizionale', fr: 'Pression de la fenêtre de sécurité conditionnelle', de: 'Druck des bedingten Sicherheitsfensters', es: 'Presión de la ventana de seguridad condicional', nl: 'Druk van het voorwaardelijke veiligheidsvenster', sv: 'Tryck i det villkorade säkerhetsfönstret', pl: 'Presja warunkowego okna bezpieczeństwa'),
            description: $this->shared->t(en: 'Editorial temporal paths from a common 2026 baseline to conditional scenario deadlines after winter 2027, at end-2030 and at end-2035.', it: 'Percorsi temporali editoriali da una base comune 2026 a scadenze condizionali dopo l’inverno 2027, a fine 2030 e a fine 2035.', fr: 'Trajectoires temporelles éditoriales depuis une base commune en 2026 vers des échéances conditionnelles après l’hiver 2027, fin 2030 et fin 2035.', de: 'Redaktionelle Zeitpfade von einer gemeinsamen Basis 2026 zu bedingten Szenariofristen nach dem Winter 2027, Ende 2030 und Ende 2035.', es: 'Trayectorias temporales editoriales desde una base común de 2026 hasta plazos condicionales después del invierno de 2027, a finales de 2030 y a finales de 2035.', nl: 'Redactionele tijdspaden van een gezamenlijke basis in 2026 naar voorwaardelijke deadlines na de winter van 2027, eind 2030 en eind 2035.', sv: 'Redaktionella tidsbanor från en gemensam bas 2026 till villkorade tidsgränser efter vintern 2027, i slutet av 2030 och i slutet av 2035.', pl: 'Redakcyjne ścieżki czasowe od wspólnej bazy 2026 do warunkowych terminów po zimie 2027, pod koniec 2030 i pod koniec 2035 roku.'),
            reasoning: $this->shared->t(
                en: 'Derived editorial time-window pressure index, not a probability, readiness score or official forecast. For year y and scenario target year t: value = min(100, round(50 + 50 × (y - 2026) / (t - 2026))). After the target year the value remains 100. Target years are 2027 pessimistic, 2030 neutral and 2035 optimistic. The pessimistic exact date is the user-selected post-winter checkpoint of 31 March 2027; no cited source derives that day.',
                it: 'Indice editoriale derivato di pressione della finestra temporale, non una probabilità, un punteggio di prontezza o una previsione ufficiale. Per l’anno y e l’anno target t: valore = min(100, round(50 + 50 × (y - 2026) / (t - 2026))). Dopo l’anno target il valore resta 100. Gli anni target sono 2027 pessimistico, 2030 neutrale e 2035 ottimistico. La data pessimistica esatta è il checkpoint post-inverno del 31 marzo 2027 scelto dall’utente; nessuna fonte citata deriva quel giorno.',
                fr: 'Indice éditorial dérivé de pression de fenêtre temporelle, ni probabilité, ni score de préparation, ni prévision officielle. Pour l’année y et l’année cible t : valeur = min(100, round(50 + 50 × (y - 2026) / (t - 2026))). Après l’année cible, la valeur reste 100. Les années cibles sont 2027 pessimiste, 2030 neutre et 2035 optimiste. La date pessimiste exacte est le jalon d’après-hiver du 31 mars 2027 choisi par l’utilisateur; aucune source citée ne dérive ce jour.',
                de: 'Abgeleiteter redaktioneller Zeitfenster-Druckindex, weder Wahrscheinlichkeit noch Bereitschaftswert oder offizielle Prognose. Für Jahr y und Zieljahr t gilt: Wert = min(100, round(50 + 50 × (y - 2026) / (t - 2026))). Nach dem Zieljahr bleibt der Wert 100. Zieljahre sind 2027 pessimistisch, 2030 neutral und 2035 optimistisch. Das genaue pessimistische Datum ist der vom Nutzer gewählte Zeitpunkt nach dem Winter am 31. März 2027; keine zitierte Quelle leitet diesen Tag ab.',
                es: 'Índice editorial derivado de presión de ventana temporal, no una probabilidad, puntuación de preparación ni previsión oficial. Para el año y y el año objetivo t: valor = min(100, round(50 + 50 × (y - 2026) / (t - 2026))). Tras el año objetivo el valor permanece en 100. Los años son 2027 pesimista, 2030 neutral y 2035 optimista. La fecha pesimista exacta es el hito posterior al invierno del 31 de marzo de 2027 elegido por el usuario; ninguna fuente citada deriva ese día.',
                nl: 'Afgeleide redactionele tijdvensterdrukindex, geen waarschijnlijkheid, paraatheidsscore of officiële voorspelling. Voor jaar y en doeljaar t: waarde = min(100, round(50 + 50 × (y - 2026) / (t - 2026))). Na het doeljaar blijft de waarde 100. Doeljaren zijn 2027 pessimistisch, 2030 neutraal en 2035 optimistisch. De exacte pessimistische datum is het door de gebruiker gekozen ijkpunt na de winter van 31 maart 2027; geen aangehaalde bron leidt die dag af.',
                sv: 'Härlett redaktionellt index för tidsfönstertryck, inte sannolikhet, beredskapspoäng eller officiell prognos. För år y och målår t: värde = min(100, round(50 + 50 × (y - 2026) / (t - 2026))). Efter målåret ligger värdet kvar på 100. Målåren är 2027 pessimistiskt, 2030 neutralt och 2035 optimistiskt. Det exakta pessimistiska datumet är den användarvalda kontrollpunkten efter vintern den 31 mars 2027; ingen citerad källa härleder den dagen.',
                pl: 'Pochodny redakcyjny indeks presji okna czasowego, a nie prawdopodobieństwo, wynik gotowości ani oficjalna prognoza. Dla roku y i roku docelowego t: wartość = min(100, round(50 + 50 × (y - 2026) / (t - 2026))). Po roku docelowym wartość pozostaje 100. Lata docelowe to 2027 pesymistyczny, 2030 neutralny i 2035 optymistyczny. Dokładna data pesymistyczna to wybrany przez użytkownika punkt po zimie 31 marca 2027 roku; żadna cytowana źródłowa ocena nie wyprowadza tego dnia.',
            ),
            labels: ['2026', '2027', '2028', '2029', '2030', '2031', '2032', '2033', '2034', '2035'],
            series: [
                ['name' => 'Pessimistic', 'color' => '#ff2a23', 'values' => [50, 100, 100, 100, 100, 100, 100, 100, 100, 100]],
                ['name' => 'Neutral', 'color' => '#38bdf8', 'values' => [50, 63, 75, 88, 100, 100, 100, 100, 100, 100]],
                ['name' => 'Optimistic', 'color' => '#22c55e', 'values' => [50, 56, 61, 67, 72, 78, 83, 89, 94, 100]],
            ],
            xLabel: 'Year',
            xType: 'temporal',
            yLabel: 'Editorial deadline pressure',
            yUnit: 'index points',
            yFormat: 'integer',
            sources: [$this->shared->sources()['ddis_russia_threat_2025'], $this->shared->sources()['nato_five_year_assessment_2025'], $this->shared->sources()['nato_2029_assessment_2026'], $this->shared->sources()['eu_readiness_roadmap_2030'], $this->shared->sources()['nato_hague_declaration'], $this->shared->sources()['nato_ankara_declaration_2026']],
            sortOrder: 1,
        );
    }

    /** @return list<array<string, mixed>> */
    public function visualizations(): array
    {
        return [
            [
                'key' => 'key_indicators',
                'type' => VisualizationType::Kpi,
                'title' => $this->shared->t(en: 'EU defence indicators 2024', it: 'Indicatori della difesa UE 2024', fr: 'Indicateurs de défense de l’UE 2024', de: 'EU-Verteidigungsindikatoren 2024', es: 'Indicadores de defensa de la UE 2024', nl: 'EU-defensie-indicatoren 2024', sv: 'EU:s försvarsindikatorer 2024', pl: 'Wskaźniki obronne UE 2024'),
                'description' => $this->shared->t(en: 'Observed spending, investment and participation values reported by EDA.', it: 'Valori osservati di spesa, investimento e partecipazione riportati dall’EDA.', fr: 'Valeurs observées de dépenses, d’investissement et de participation publiées par l’AED.', de: 'Von der EDA gemeldete beobachtete Ausgaben-, Investitions- und Beteiligungswerte.', es: 'Valores observados de gasto, inversión y participación publicados por la AED.', nl: 'Door het EDA gerapporteerde waargenomen uitgaven-, investerings- en deelnamewaarden.', sv: 'Observerade utgifts-, investerings- och deltagandevärden rapporterade av EDA.', pl: 'Zaobserwowane wartości wydatków, inwestycji i uczestnictwa raportowane przez EDA.'),
                'sources' => [$this->shared->sources()['eda_defence_data_pdf']],
                'reasoning' => $this->shared->t(en: 'Observed values transcribed from EDA Defence Data 2024-2025: €343bn total expenditure, 1.9% of GDP, €106bn investment, €88bn equipment procurement, €13bn R&D, and 13 member states at or above 2% of GDP. Incompatible units are intentionally separate KPI items.', it: 'Valori osservati trascritti da EDA Defence Data 2024-2025: €343 mld di spesa totale, 1,9% del PIL, €106 mld di investimenti, €88 mld di acquisti, €13 mld di R&S e 13 Stati membri almeno al 2% del PIL. Le unità incompatibili restano KPI separati.', fr: 'Valeurs observées transcrites des données AED 2024-2025 : 343 Md€ de dépenses, 1,9% du PIB, 106 Md€ d’investissement, 88 Md€ d’achats, 13 Md€ de R&D et 13 États membres à au moins 2% du PIB. Les unités incompatibles restent des KPI séparés.', de: 'Beobachtete Werte aus EDA Defence Data 2024-2025: 343 Mrd. € Gesamtausgaben, 1,9% des BIP, 106 Mrd. € Investitionen, 88 Mrd. € Beschaffung, 13 Mrd. € F&E und 13 Mitgliedstaaten bei mindestens 2% des BIP. Unvereinbare Einheiten bleiben getrennte KPI.', es: 'Valores observados de EDA Defence Data 2024-2025: 343.000 M€ de gasto, 1,9% del PIB, 106.000 M€ de inversión, 88.000 M€ de compras, 13.000 M€ de I+D y 13 Estados al menos en 2% del PIB. Las unidades incompatibles son KPI separados.', nl: 'Waargenomen waarden uit EDA Defence Data 2024-2025: €343 mld totaal, 1,9% bbp, €106 mld investeringen, €88 mld materieelaankopen, €13 mld O&O en 13 lidstaten op minstens 2% bbp. Onverenigbare eenheden staan als aparte KPI.', sv: 'Observerade värden från EDA Defence Data 2024-2025: 343 md euro totalt, 1,9% av BNP, 106 md investeringar, 88 md materielanskaffning, 13 md FoU och 13 medlemsstater på minst 2% av BNP. Oförenliga enheter visas som separata KPI.', pl: 'Wartości obserwowane z EDA Defence Data 2024-2025: 343 mld euro wydatków, 1,9% PKB, 106 mld inwestycji, 88 mld zakupów, 13 mld B+R i 13 państw co najmniej na poziomie 2% PKB. Niezgodne jednostki pozostają oddzielnymi KPI.'),
                'payload' => ['items' => [
                    ['label' => 'Total defence expenditure', 'value' => '€343bn'],
                    ['label' => 'Share of EU GDP', 'value' => '1.9%'],
                    ['label' => 'Defence investment', 'value' => '€106bn'],
                    ['label' => 'Equipment procurement', 'value' => '€88bn'],
                    ['label' => 'Defence R&D', 'value' => '€13bn'],
                    ['label' => 'Member states at or above 2%', 'value' => '13'],
                ]],
                'schema_version' => 1,
                'sort_order' => 1,
            ],
            $this->shared->chartVisualization(
                key: 'nato_spending_share_trend',
                type: VisualizationType::Line,
                title: $this->shared->t(en: 'NATO Europe and Canada spending share', it: 'Quota di spesa NATO Europa e Canada', fr: 'Part des dépenses OTAN Europe et Canada', de: 'Ausgabenanteil NATO Europa und Kanada', es: 'Cuota de gasto de OTAN Europa y Canadá', nl: 'Uitgavenaandeel NAVO Europa en Canada', sv: 'Utgiftsandel Nato Europa och Kanada', pl: 'Udział wydatków NATO Europa i Kanada'),
                description: $this->shared->t(en: 'Defence expenditure as a share of real GDP, 2014-2025 estimate.', it: 'Spesa per la difesa in quota del PIL reale, 2014-stima 2025.', fr: 'Dépenses de défense en part du PIB réel, 2014-estimation 2025.', de: 'Verteidigungsausgaben als Anteil des realen BIP, 2014-Schätzung 2025.', es: 'Gasto en defensa como porcentaje del PIB real, 2014-estimación 2025.', nl: 'Defensie-uitgaven als aandeel van reëel bbp, 2014-raming 2025.', sv: 'Försvarsutgifter som andel av real BNP, 2014-prognos 2025.', pl: 'Wydatki obronne jako udział realnego PKB, 2014-szacunek 2025.'),
                reasoning: $this->shared->t(en: 'Observed NATO aggregate values for 2014-2023 and NATO estimates for 2024-2025 are transcribed without interpolation. NATO notes that aggregate membership changes over the series, adding Montenegro, North Macedonia, Finland and Sweden in their accession years.', it: 'Valori aggregati NATO osservati 2014-2023 e stime NATO 2024-2025 trascritti senza interpolazione. La NATO segnala che la composizione cambia con l’ingresso di Montenegro, Macedonia del Nord, Finlandia e Svezia.', fr: 'Valeurs agrégées OTAN observées 2014-2023 et estimations 2024-2025 transcrites sans interpolation. L’OTAN indique que la composition change avec les adhésions du Monténégro, de la Macédoine du Nord, de la Finlande et de la Suède.', de: 'Beobachtete NATO-Aggregate 2014-2023 und NATO-Schätzungen 2024-2025 ohne Interpolation. Die NATO weist auf Änderungen der Zusammensetzung durch Montenegro, Nordmazedonien, Finnland und Schweden hin.', es: 'Valores agregados observados de la OTAN 2014-2023 y estimaciones 2024-2025 transcritos sin interpolación. La OTAN señala cambios de composición con Montenegro, Macedonia del Norte, Finlandia y Suecia.', nl: 'Waargenomen NAVO-aggregaten 2014-2023 en NAVO-ramingen 2024-2025 zonder interpolatie. De NAVO vermeldt samenstellingswijzigingen door Montenegro, Noord-Macedonië, Finland en Zweden.', sv: 'Observerade Nato-aggregat 2014-2023 och Nato-estimat 2024-2025 utan interpolering. Nato anger att sammansättningen ändras när Montenegro, Nordmakedonien, Finland och Sverige ansluter.', pl: 'Zaobserwowane agregaty NATO 2014-2023 i szacunki 2024-2025 przepisano bez interpolacji. NATO zaznacza zmiany składu po przystąpieniu Czarnogóry, Macedonii Północnej, Finlandii i Szwecji.'),
                labels: ['2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024e', '2025e'],
                series: [1.40, 1.40, 1.41, 1.45, 1.48, 1.51, 1.69, 1.63, 1.63, 1.74, 1.99, 2.27],
                xLabel: 'Year', xType: 'temporal', yLabel: 'Defence expenditure share', yUnit: '% of real GDP', yFormat: 'decimal',
                sources: [$this->shared->sources()['nato_expenditure_2025_pdf']], sortOrder: 2,
            ),
            $this->shared->chartVisualization(
                key: 'nato_real_spending_trend',
                type: VisualizationType::Area,
                title: $this->shared->t(en: 'NATO Europe and Canada real spending', it: 'Spesa reale NATO Europa e Canada', fr: 'Dépenses réelles OTAN Europe et Canada', de: 'Reale Ausgaben NATO Europa und Kanada', es: 'Gasto real de OTAN Europa y Canadá', nl: 'Reële uitgaven NAVO Europa en Canada', sv: 'Reala utgifter Nato Europa och Kanada', pl: 'Realne wydatki NATO Europa i Kanada'),
                description: $this->shared->t(en: 'Defence expenditure in constant 2021 US dollars.', it: 'Spesa per la difesa in dollari USA costanti 2021.', fr: 'Dépenses de défense en dollars US constants de 2021.', de: 'Verteidigungsausgaben in konstanten US-Dollar von 2021.', es: 'Gasto en defensa en dólares constantes de 2021.', nl: 'Defensie-uitgaven in constante Amerikaanse dollars van 2021.', sv: 'Försvarsutgifter i konstanta 2021 års US-dollar.', pl: 'Wydatki obronne w stałych dolarach USA z 2021 roku.'),
                reasoning: $this->shared->t(en: 'Observed NATO Europe and Canada totals for 2014-2023 and NATO estimates for 2024-2025, copied from the constant-2021-price table. Values are millions of US dollars and no currency conversion or interpolation is added.', it: 'Totali osservati NATO Europa e Canada 2014-2023 e stime 2024-2025 dalla tabella a prezzi costanti 2021. Valori in milioni di dollari USA, senza conversioni o interpolazioni aggiuntive.', fr: 'Totaux observés OTAN Europe et Canada 2014-2023 et estimations 2024-2025 issus du tableau à prix constants 2021. Valeurs en millions de dollars US, sans conversion ni interpolation ajoutée.', de: 'Beobachtete Summen NATO Europa und Kanada 2014-2023 und Schätzungen 2024-2025 aus der Tabelle zu konstanten Preisen von 2021. Werte in Mio. US-Dollar, ohne zusätzliche Umrechnung oder Interpolation.', es: 'Totales observados OTAN Europa y Canadá 2014-2023 y estimaciones 2024-2025 de la tabla a precios constantes de 2021. Valores en millones de dólares, sin conversión ni interpolación.', nl: 'Waargenomen totalen NAVO Europa en Canada 2014-2023 en ramingen 2024-2025 uit de tabel met constante 2021-prijzen. Waarden in miljoenen US-dollar, zonder extra conversie of interpolatie.', sv: 'Observerade totalsummor för Nato Europa och Kanada 2014-2023 och estimat 2024-2025 från tabellen i fasta 2021-priser. Värden i miljoner US-dollar utan extra omräkning eller interpolering.', pl: 'Zaobserwowane sumy NATO Europa i Kanada 2014-2023 oraz szacunki 2024-2025 z tabeli w cenach stałych z 2021 roku. Wartości w mln USD, bez dodatkowej konwersji lub interpolacji.'),
                labels: ['2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024e', '2025e'],
                series: [278589, 283767, 291748, 309146, 321215, 333716, 349702, 358668, 372255, 406766, 482395, 559305],
                xLabel: 'Year', xType: 'temporal', yLabel: 'Real defence expenditure', yUnit: 'US$ million, 2021 prices', yFormat: 'integer',
                sources: [$this->shared->sources()['nato_expenditure_2025_pdf']], sortOrder: 3,
            ),
            $this->shared->chartVisualization(
                key: 'selected_allies_2025',
                type: VisualizationType::Bar,
                title: $this->shared->t(en: 'Selected European allies, 2025 estimate', it: 'Alleati europei selezionati, stima 2025', fr: 'Alliés européens sélectionnés, estimation 2025', de: 'Ausgewählte europäische Alliierte, Schätzung 2025', es: 'Aliados europeos seleccionados, estimación 2025', nl: 'Geselecteerde Europese bondgenoten, raming 2025', sv: 'Utvalda europeiska allierade, estimat 2025', pl: 'Wybrani europejscy sojusznicy, szacunek 2025'),
                description: $this->shared->t(en: 'Estimated defence expenditure shares for a selected cross-section of European allies.', it: 'Quote stimate di spesa per la difesa per una selezione di alleati europei.', fr: 'Parts estimées des dépenses de défense pour une sélection d’alliés européens.', de: 'Geschätzte Verteidigungsausgabenanteile ausgewählter europäischer Alliierter.', es: 'Porcentajes estimados de gasto en defensa para una selección de aliados europeos.', nl: 'Geraamde defensie-uitgavenaandelen voor een selectie Europese bondgenoten.', sv: 'Beräknade försvarsutgiftsandelar för ett urval europeiska allierade.', pl: 'Szacowane udziały wydatków obronnych dla wybranych europejskich sojuszników.'),
                reasoning: $this->shared->t(en: 'Observed as NATO 2025 estimates, not final accounts. The ten countries are a transparent selected cross-section, not an EU or NATO average: Poland 4.48, Lithuania 4.00, Latvia 3.73, Estonia 3.38, Norway 3.35, Denmark 3.22, Sweden 2.51, Netherlands 2.49, United Kingdom 2.40 and France 2.05 percent of real GDP.', it: 'Stime NATO 2025, non conti definitivi. I dieci paesi sono una selezione trasparente, non una media UE o NATO.', fr: 'Estimations OTAN 2025, et non comptes définitifs. Les dix pays forment un échantillon transparent, pas une moyenne UE ou OTAN.', de: 'NATO-Schätzungen 2025, keine endgültigen Abschlüsse. Die zehn Länder sind eine transparente Auswahl, kein EU- oder NATO-Durchschnitt.', es: 'Estimaciones OTAN 2025, no cuentas definitivas. Los diez países son una selección transparente, no una media de la UE u OTAN.', nl: 'NAVO-ramingen voor 2025, geen definitieve rekeningen. De tien landen zijn een transparante selectie, geen EU- of NAVO-gemiddelde.', sv: 'Nato-estimat för 2025, inte slutliga utfall. De tio länderna är ett öppet urval, inte ett EU- eller Nato-genomsnitt.', pl: 'Szacunki NATO na 2025 rok, nie dane ostateczne. Dziesięć państw to jawny wybór, a nie średnia UE lub NATO.'),
                labels: ['Poland', 'Lithuania', 'Latvia', 'Estonia', 'Norway', 'Denmark', 'Sweden', 'Netherlands', 'United Kingdom', 'France'],
                series: [4.48, 4.00, 3.73, 3.38, 3.35, 3.22, 2.51, 2.49, 2.40, 2.05],
                xLabel: 'Ally', xType: 'category', yLabel: 'Estimated defence expenditure share', yUnit: '% of real GDP', yFormat: 'decimal',
                sources: [$this->shared->sources()['nato_expenditure_2025_pdf']], sortOrder: 4,
            ),
            $this->shared->chartVisualization(
                key: 'eu_investment_mix_2024',
                type: VisualizationType::Bar,
                title: $this->shared->t(en: 'EU defence spending components 2024', it: 'Componenti della spesa UE per la difesa 2024', fr: 'Composantes des dépenses de défense de l’UE 2024', de: 'Komponenten der EU-Verteidigungsausgaben 2024', es: 'Componentes del gasto de defensa de la UE 2024', nl: 'Componenten van EU-defensie-uitgaven 2024', sv: 'Komponenter i EU:s försvarsutgifter 2024', pl: 'Składniki wydatków obronnych UE 2024'),
                description: $this->shared->t(en: 'Observed spending categories in constant 2024 euros.', it: 'Categorie di spesa osservate in euro costanti 2024.', fr: 'Catégories de dépenses observées en euros constants de 2024.', de: 'Beobachtete Ausgabenkategorien in konstanten Euro von 2024.', es: 'Categorías observadas en euros constantes de 2024.', nl: 'Waargenomen categorieën in constante euro’s van 2024.', sv: 'Observerade kategorier i fasta 2024-euro.', pl: 'Zaobserwowane kategorie w stałych euro z 2024 roku.'),
                reasoning: $this->shared->t(en: 'Observed EDA values: total expenditure €343bn, investment €106bn, equipment procurement €88bn, R&D €13bn and R&T €5bn. Investment, procurement, R&D and R&T are nested categories, so the bars must not be summed; they are shown only on a common €bn scale.', it: 'Valori EDA osservati: totale €343 mld, investimenti €106 mld, acquisti €88 mld, R&S €13 mld e R&T €5 mld. Le categorie sono annidate e non vanno sommate; condividono solo la scala in miliardi di euro.', fr: 'Valeurs AED observées : total 343 Md€, investissement 106 Md€, achats 88 Md€, R&D 13 Md€ et R&T 5 Md€. Les catégories sont imbriquées et ne doivent pas être additionnées.', de: 'Beobachtete EDA-Werte: Gesamt 343 Mrd. €, Investitionen 106, Beschaffung 88, F&E 13 und F&T 5 Mrd. €. Die Kategorien sind verschachtelt und dürfen nicht addiert werden.', es: 'Valores AED observados: total 343.000 M€, inversión 106.000 M€, compras 88.000 M€, I+D 13.000 M€ e I+T 5.000 M€. Las categorías están anidadas y no deben sumarse.', nl: 'Waargenomen EDA-waarden: totaal €343 mld, investeringen €106 mld, aankopen €88 mld, O&O €13 mld en O&T €5 mld. De categorieën zijn genest en mogen niet worden opgeteld.', sv: 'Observerade EDA-värden: totalt 343 md euro, investeringar 106, materiel 88, FoU 13 och FoT 5 md euro. Kategorierna är inbäddade och får inte summeras.', pl: 'Wartości EDA: ogółem 343 mld euro, inwestycje 106, zakupy 88, B+R 13 i badania technologiczne 5 mld euro. Kategorie są zagnieżdżone i nie wolno ich sumować.'),
                labels: ['Total expenditure', 'Defence investment', 'Equipment procurement', 'R&D', 'R&T'],
                series: [343, 106, 88, 13, 5],
                xLabel: 'Spending category', xType: 'category', yLabel: 'Expenditure', yUnit: '€ billion, 2024 prices', yFormat: 'integer',
                sources: [$this->shared->sources()['eda_defence_data_pdf']], sortOrder: 5,
            ),
            [
                'key' => 'readiness_instruments',
                'type' => VisualizationType::Kpi,
                'title' => $this->shared->t(en: 'Readiness instruments', it: 'Strumenti di prontezza', fr: 'Instruments de préparation', de: 'Bereitschaftsinstrumente', es: 'Instrumentos de preparación', nl: 'Paraatheidsinstrumenten', sv: 'Beredskapsinstrument', pl: 'Instrumenty gotowości'),
                'description' => $this->shared->t(en: 'Official production and financing objectives kept as separate units.', it: 'Obiettivi ufficiali di produzione e finanziamento mantenuti in unità separate.', fr: 'Objectifs officiels de production et de financement conservés dans des unités séparées.', de: 'Offizielle Produktions- und Finanzierungsziele in getrennten Einheiten.', es: 'Objetivos oficiales de producción y financiación en unidades separadas.', nl: 'Officiële productie- en financieringsdoelen in afzonderlijke eenheden.', sv: 'Officiella produktions- och finansieringsmål i separata enheter.', pl: 'Oficjalne cele produkcyjne i finansowe w oddzielnych jednostkach.'),
                'sources' => [$this->shared->sources()['white_paper_pdf'], $this->shared->sources()['safe_council'], $this->shared->sources()['future_defence']],
                'reasoning' => $this->shared->t(en: 'Observed policy objectives: a minimum capacity objective of 2 million large-calibre artillery rounds per year, up to €150bn in SAFE loans, and an intended mobilisation of up to €800bn under Readiness 2030. These values use incompatible units and are therefore separate KPI items, not a chart series or a sum.', it: 'Obiettivi politici osservati: minimo 2 milioni di colpi di grosso calibro l’anno, fino a €150 mld di prestiti SAFE e mobilitazione fino a €800 mld con Readiness 2030. Unità incompatibili, quindi KPI separati e non sommabili.', fr: 'Objectifs politiques observés : minimum 2 millions d’obus de gros calibre par an, jusqu’à 150 Md€ de prêts SAFE et jusqu’à 800 Md€ à mobiliser avec Readiness 2030. Unités incompatibles, donc KPI séparés.', de: 'Beobachtete Politikziele: mindestens 2 Mio. großkalibrige Artilleriegeschosse pro Jahr, bis zu 150 Mrd. € SAFE-Darlehen und bis zu 800 Mrd. € Mobilisierung durch Readiness 2030. Unvereinbare Einheiten bleiben getrennte KPI.', es: 'Objetivos observados: mínimo 2 millones de proyectiles de gran calibre al año, hasta 150.000 M€ en préstamos SAFE y hasta 800.000 M€ de movilización Readiness 2030. Son unidades incompatibles y KPI separados.', nl: 'Waargenomen beleidsdoelen: minimaal 2 miljoen grootkalibergranaten per jaar, tot €150 mld SAFE-leningen en tot €800 mld mobilisatie via Readiness 2030. Onverenigbare eenheden blijven aparte KPI.', sv: 'Observerade policymål: minst 2 miljoner grovkalibriga granater per år, upp till 150 md euro i SAFE-lån och upp till 800 md euro mobilisering genom Readiness 2030. Oförenliga enheter visas separat.', pl: 'Zaobserwowane cele polityczne: co najmniej 2 mln pocisków dużego kalibru rocznie, do 150 mld euro pożyczek SAFE i do 800 mld euro mobilizacji Readiness 2030. Niezgodne jednostki pozostają oddzielnymi KPI.'),
                'payload' => ['items' => [
                    ['label' => 'Large-calibre rounds objective', 'value' => '2m/year'],
                    ['label' => 'SAFE loan capacity', 'value' => 'up to €150bn'],
                    ['label' => 'Readiness 2030 mobilisation', 'value' => 'up to €800bn'],
                ]],
                'schema_version' => 1,
                'sort_order' => 6,
            ],
        ];
    }
};
