<?php

declare(strict_types=1);

use App\Enums\CountdownSeverity;
use App\Enums\CountdownStatus;
use Carbon\CarbonImmutable;

$shared = require __DIR__.'/../_shared.php';

return new class($shared)
{
    public function __construct(private object $shared) {}

    /** @return array<string, mixed> */
    public function countdown(): array
    {
        return [
            'slug' => $this->shared::SLUG,
            'title' => $this->shared->t(
                en: 'Europe on the Brink: The War Countdown',
                it: 'Europa sull’orlo: la guerra alle porte',
                fr: 'L’Europe au bord du gouffre : le compte à rebours de la guerre',
                de: 'Europa am Abgrund: Der Kriegs-Countdown',
                es: 'Europa al límite: la cuenta atrás de la guerra',
                nl: 'Europa op de rand: de oorlogsaftelling',
                sv: 'Europa på randen: nedräkningen till krig',
                pl: 'Europa na krawędzi: odliczanie do wojny',
            ),
            'summary' => $this->shared->t(
                en: 'The active chain starts with a user-selected Pessimistic checkpoint on 31 March 2027, then moves to the Neutral NATO/EU readiness checkpoint at end-2030 and the Optimistic investment/readiness horizon at end-2035; these are conditional editorial deadlines, not a prediction of war.',
                it: 'La catena attiva parte dal checkpoint Pessimistico del 31 marzo 2027 scelto dall’utente, passa al checkpoint Neutrale di prontezza NATO/UE a fine 2030 e all’orizzonte Ottimistico di investimento/prontezza a fine 2035; sono scadenze editoriali condizionali, non una previsione di guerra.',
                fr: 'La chaîne active commence par le jalon Pessimiste du 31 mars 2027 choisi par l’utilisateur, puis passe au jalon Neutre de préparation OTAN/UE fin 2030 et à l’horizon Optimiste d’investissement et de préparation fin 2035; ce sont des échéances éditoriales conditionnelles, pas une prédiction de guerre.',
                de: 'Die aktive Kette beginnt mit dem vom Nutzer gewählten pessimistischen Prüfpunkt am 31. März 2027, führt zum neutralen NATO/EU-Bereitschaftspunkt Ende 2030 und zum optimistischen Investitions- und Bereitschaftshorizont Ende 2035; dies sind bedingte redaktionelle Fristen, keine Kriegsprognose.',
                es: 'La cadena activa comienza con el hito Pesimista del 31 de marzo de 2027 elegido por el usuario, continúa con el hito Neutral de preparación OTAN/UE de finales de 2030 y el horizonte Optimista de inversión y preparación de finales de 2035; son plazos editoriales condicionales, no una predicción de guerra.',
                nl: 'De actieve keten begint met het door de gebruiker gekozen Pessimistische ijkpunt op 31 maart 2027, gaat daarna naar het Neutrale NAVO/EU-paraatheidsijkpunt eind 2030 en het Optimistische investerings- en paraatheidshorizon eind 2035; dit zijn voorwaardelijke redactionele termijnen, geen oorlogsvoorspelling.',
                sv: 'Den aktiva kedjan börjar med den användarvalda Pessimistiska kontrollpunkten den 31 mars 2027, går vidare till den Neutrala Nato/EU-beredskapspunkten i slutet av 2030 och den Optimistiska investerings- och beredskapshorisonten i slutet av 2035; detta är villkorade redaktionella tidsgränser, inte en krigsprognos.',
                pl: 'Aktywny łańcuch zaczyna się od wybranego przez użytkownika Pesymistycznego punktu 31 marca 2027 roku, następnie przechodzi do Neutralnego punktu gotowości NATO/UE pod koniec 2030 roku i Optymistycznego horyzontu inwestycji i gotowości pod koniec 2035 roku; są to warunkowe terminy redakcyjne, a nie prognoza wojny.',
            ),
            'description' => $this->shared->t(
                en: 'The active Pessimistic checkpoint is 31 March 2027, a user-selected post-winter editorial deadline; no cited source identifies it as an attack date. The chain then moves to the Neutral end-2030 readiness checkpoint, where NATO’s public 2029/end-decade assessments meet EU requirements for critical contracts by end-2028 and SAFE deliveries by end-2030, and finally to the Optimistic end-2035 investment/readiness horizon if EU and NATO delivery matures. All three dates are conditional editorial checkpoints, not forecasts of intent or certain war dates.',
                it: 'Il checkpoint Pessimistico attivo è il 31 marzo 2027, una scadenza editoriale post-inverno scelta dall’utente; nessuna fonte citata lo identifica come data di attacco. La catena passa quindi al checkpoint Neutrale di prontezza a fine 2030, dove le valutazioni pubbliche NATO sul 2029/fine decennio incontrano i requisiti UE per contratti critici entro fine 2028 e consegne SAFE entro fine 2030, e infine all’orizzonte Ottimistico di investimento/prontezza a fine 2035 se maturano le consegne UE e NATO. Tutte e tre le date sono checkpoint editoriali condizionali, non previsioni di intenzione o date certe di guerra.',
                fr: 'Le jalon Pessimiste actif est le 31 mars 2027, une échéance éditoriale d’après-hiver choisie par l’utilisateur; aucune source citée ne l’identifie comme date d’attaque. La chaîne passe ensuite au jalon Neutre de préparation fin 2030, où les évaluations publiques de l’OTAN pour 2029/la fin de décennie rencontrent les exigences de l’UE pour des contrats critiques fin 2028 et des livraisons SAFE fin 2030, puis à l’horizon Optimiste d’investissement et de préparation fin 2035 si les livraisons de l’UE et de l’OTAN arrivent à maturité. Ces trois dates sont des jalons éditoriaux conditionnels, pas des prévisions d’intention ni des dates certaines de guerre.',
                de: 'Der aktive pessimistische Prüfpunkt ist der 31. März 2027, eine vom Nutzer gewählte redaktionelle Frist nach dem Winter; keine zitierte Quelle nennt ihn als Angriffsdatum. Die Kette führt dann zum neutralen Bereitschaftspunkt Ende 2030, an dem die öffentlichen NATO-Bewertungen für 2029/das Jahrzehntende auf die EU-Anforderungen für kritische Verträge bis Ende 2028 und SAFE-Lieferungen bis Ende 2030 treffen, und schließlich zum optimistischen Investitions- und Bereitschaftshorizont Ende 2035, wenn EU- und NATO-Lieferungen ausreifen. Alle drei Daten sind bedingte redaktionelle Prüfpunkte, keine Prognosen von Absicht oder sicheren Kriegsdaten.',
                es: 'El hito Pesimista activo es el 31 de marzo de 2027, un plazo editorial posterior al invierno elegido por el usuario; ninguna fuente citada lo identifica como fecha de ataque. La cadena pasa después al hito Neutral de preparación de finales de 2030, donde las evaluaciones públicas de la OTAN sobre 2029/final de década coinciden con los requisitos de la UE para contratos críticos a finales de 2028 y entregas SAFE a finales de 2030, y finalmente al horizonte Optimista de inversión y preparación de finales de 2035 si maduran las entregas de la UE y la OTAN. Las tres fechas son hitos editoriales condicionales, no previsiones de intención ni fechas ciertas de guerra.',
                nl: 'Het actieve Pessimistische ijkpunt is 31 maart 2027, een door de gebruiker gekozen redactionele deadline na de winter; geen aangehaalde bron noemt dit als aanvalsdatum. De keten gaat daarna naar het Neutrale paraatheidsijkpunt eind 2030, waar openbare NAVO-beoordelingen voor 2029/einde decennium samenkomen met EU-eisen voor kritieke contracten eind 2028 en SAFE-leveringen eind 2030, en vervolgens naar de Optimistische investerings- en paraatheidshorizon eind 2035 als EU- en NAVO-leveringen rijpen. Alle drie de data zijn voorwaardelijke redactionele ijkpunten, geen voorspellingen van intentie of zekere oorlogsdata.',
                sv: 'Den aktiva Pessimistiska kontrollpunkten är den 31 mars 2027, en användarvald redaktionell tidsgräns efter vintern; ingen citerad källa anger den som ett angreppsdatum. Kedjan går därefter till den Neutrala beredskapspunkten i slutet av 2030, där Natos offentliga bedömningar för 2029/årtiondets slut möter EU:s krav på kritiska kontrakt senast 2028 och SAFE-leveranser senast 2030, och slutligen till den Optimistiska investerings- och beredskapshorisonten i slutet av 2035 om EU:s och Natos leveranser mognar. Alla tre datum är villkorade redaktionella kontrollpunkter, inte prognoser om avsikt eller säkra krigsdatum.',
                pl: 'Aktywnym Pesymistycznym punktem jest 31 marca 2027 roku, wybrany przez użytkownika redakcyjny termin po zimie; żadna cytowana źródłowa ocena nie wskazuje go jako daty ataku. Łańcuch przechodzi następnie do Neutralnego punktu gotowości pod koniec 2030 roku, gdzie publiczne oceny NATO dotyczące 2029/końca dekady spotykają się z wymogami UE dotyczącymi kluczowych kontraktów do końca 2028 roku i dostaw SAFE do końca 2030 roku, a następnie do Optymistycznego horyzontu inwestycji i gotowości pod koniec 2035 roku, jeśli dojrzeją dostawy UE i NATO. Wszystkie trzy daty są warunkowymi punktami redakcyjnymi, a nie prognozami intencji ani pewnymi datami wojny.'
            ),
            'causes' => $this->shared->tl(
                en: ['Russia’s war against Ukraine and persistent coercive pressure.', 'Long-standing capability, stockpile and industrial-production gaps.', 'Fragmented procurement and slow cross-border military mobility.', 'Hybrid, cyber and infrastructure threats below the threshold of open war.'],
                it: ['La guerra russa contro l’Ucraina e la persistente pressione coercitiva.', 'Divari di lunga durata in capacità, scorte e produzione industriale.', 'Acquisti frammentati e mobilità militare transfrontaliera lenta.', 'Minacce ibride, cyber e alle infrastrutture sotto la soglia della guerra aperta.'],
                fr: ['La guerre russe contre l’Ukraine et la pression coercitive persistante.', 'Des lacunes durables en capacités, stocks et production industrielle.', 'Des achats fragmentés et une mobilité militaire transfrontalière lente.', 'Des menaces hybrides, cyber et infrastructurelles sous le seuil de la guerre ouverte.'],
                de: ['Russlands Krieg gegen die Ukraine und anhaltender Zwangsdruck.', 'Langjährige Lücken bei Fähigkeiten, Beständen und Industrieproduktion.', 'Fragmentierte Beschaffung und langsame grenzüberschreitende Militärmobilität.', 'Hybride, Cyber- und Infrastrukturbedrohungen unterhalb der offenen Kriegsschwelle.'],
                es: ['La guerra de Rusia contra Ucrania y la presión coercitiva persistente.', 'Brechas duraderas de capacidades, reservas y producción industrial.', 'Contratación fragmentada y movilidad militar transfronteriza lenta.', 'Amenazas híbridas, cibernéticas y de infraestructura por debajo de la guerra abierta.'],
                nl: ['Ruslands oorlog tegen Oekraïne en aanhoudende dwangdruk.', 'Langdurige tekorten aan capaciteiten, voorraden en industriële productie.', 'Versnipperde aanbesteding en trage grensoverschrijdende militaire mobiliteit.', 'Hybride, cyber- en infrastructuurdreigingen onder de drempel van open oorlog.'],
                sv: ['Rysslands krig mot Ukraina och ihållande tvångstryck.', 'Långvariga luckor i förmåga, lager och industriproduktion.', 'Splittrad upphandling och långsam gränsöverskridande militär rörlighet.', 'Hybrid-, cyber- och infrastrukturhot under tröskeln för öppet krig.'],
                pl: ['Wojna Rosji przeciw Ukrainie i trwała presja przymusu.', 'Długotrwałe luki w zdolnościach, zapasach i produkcji przemysłowej.', 'Rozdrobnione zamówienia i powolna transgraniczna mobilność wojskowa.', 'Zagrożenia hybrydowe, cybernetyczne i infrastrukturalne poniżej progu otwartej wojny.'],
            ),
            'consequences' => $this->shared->tl(
                en: ['A deterrence gap can increase the risk of coercion or miscalculation.', 'Insufficient air defence, ammunition and logistics can slow collective response.', 'Emergency procurement can raise costs and reduce interoperability.', 'Civil infrastructure and democratic institutions remain exposed to hybrid pressure.'],
                it: ['Un divario di deterrenza può aumentare il rischio di coercizione o errore di calcolo.', 'Difesa aerea, munizioni e logistica insufficienti possono rallentare la risposta collettiva.', 'Gli acquisti d’emergenza possono aumentare i costi e ridurre l’interoperabilità.', 'Infrastrutture civili e istituzioni democratiche restano esposte alla pressione ibrida.'],
                fr: ['Un déficit de dissuasion peut accroître le risque de coercition ou d’erreur de calcul.', 'Une défense aérienne, des munitions et une logistique insuffisantes peuvent ralentir la réponse collective.', 'Les achats d’urgence peuvent augmenter les coûts et réduire l’interopérabilité.', 'Les infrastructures civiles et les institutions démocratiques restent exposées à la pression hybride.'],
                de: ['Eine Abschreckungslücke kann Zwang oder Fehlkalkulationen wahrscheinlicher machen.', 'Unzureichende Luftverteidigung, Munition und Logistik können die gemeinsame Reaktion bremsen.', 'Notbeschaffung kann Kosten erhöhen und Interoperabilität verringern.', 'Zivile Infrastruktur und demokratische Institutionen bleiben hybridem Druck ausgesetzt.'],
                es: ['Una brecha de disuasión puede aumentar el riesgo de coerción o error de cálculo.', 'Una defensa aérea, munición y logística insuficientes pueden ralentizar la respuesta colectiva.', 'La contratación de emergencia puede elevar costes y reducir interoperabilidad.', 'Las infraestructuras civiles y las instituciones democráticas siguen expuestas a presión híbrida.'],
                nl: ['Een afschrikkingskloof kan het risico op dwang of misrekening vergroten.', 'Onvoldoende luchtverdediging, munitie en logistiek kunnen de gezamenlijke reactie vertragen.', 'Noodaankopen kunnen kosten verhogen en interoperabiliteit verlagen.', 'Civiele infrastructuur en democratische instellingen blijven blootstaan aan hybride druk.'],
                sv: ['Ett avskräckningsgap kan öka risken för tvång eller felbedömning.', 'Otillräckligt luftförsvar, ammunition och logistik kan bromsa det gemensamma svaret.', 'Akut upphandling kan höja kostnader och minska interoperabilitet.', 'Civil infrastruktur och demokratiska institutioner förblir utsatta för hybridtryck.'],
                pl: ['Luka odstraszania może zwiększyć ryzyko przymusu lub błędnej kalkulacji.', 'Niewystarczająca obrona powietrzna, amunicja i logistyka mogą spowolnić wspólną reakcję.', 'Zakupy awaryjne mogą podnosić koszty i ograniczać interoperacyjność.', 'Infrastruktura cywilna i instytucje demokratyczne pozostają narażone na presję hybrydową.'],
            ),
            'recommended_actions' => $this->shared->tl(
                en: ['Track official spending and delivery data rather than political announcements alone.', 'Prioritise joint procurement, ammunition, air defence and military mobility.', 'Measure industrial output and delivery milestones against Readiness 2030 objectives.', 'Strengthen civil resilience, infrastructure protection and democratic safeguards.'],
                it: ['Seguire dati ufficiali su spesa e consegne, non solo annunci politici.', 'Dare priorità ad acquisti comuni, munizioni, difesa aerea e mobilità militare.', 'Misurare produzione e consegne rispetto agli obiettivi Readiness 2030.', 'Rafforzare resilienza civile, protezione delle infrastrutture e garanzie democratiche.'],
                fr: ['Suivre les données officielles de dépenses et de livraisons plutôt que les seules annonces politiques.', 'Prioriser les achats communs, les munitions, la défense aérienne et la mobilité militaire.', 'Mesurer production et livraisons par rapport aux objectifs Readiness 2030.', 'Renforcer la résilience civile, la protection des infrastructures et les garanties démocratiques.'],
                de: ['Offizielle Ausgaben- und Lieferdaten statt nur politischer Ankündigungen verfolgen.', 'Gemeinsame Beschaffung, Munition, Luftverteidigung und Militärmobilität priorisieren.', 'Industrieproduktion und Liefermeilensteine an Readiness-2030-Zielen messen.', 'Zivile Resilienz, Infrastrukturschutz und demokratische Sicherungen stärken.'],
                es: ['Seguir datos oficiales de gasto y entregas, no solo anuncios políticos.', 'Priorizar contratación conjunta, munición, defensa aérea y movilidad militar.', 'Medir producción y entregas frente a los objetivos Readiness 2030.', 'Reforzar resiliencia civil, protección de infraestructuras y salvaguardias democráticas.'],
                nl: ['Volg officiële uitgaven- en leveringsgegevens, niet alleen politieke aankondigingen.', 'Geef prioriteit aan gezamenlijke inkoop, munitie, luchtverdediging en militaire mobiliteit.', 'Meet productie en leveringen aan de doelstellingen van Readiness 2030.', 'Versterk civiele weerbaarheid, infrastructuurbescherming en democratische waarborgen.'],
                sv: ['Följ officiella utgifts- och leveransdata, inte bara politiska tillkännagivanden.', 'Prioritera gemensam upphandling, ammunition, luftförsvar och militär rörlighet.', 'Mät industriproduktion och leveranser mot Readiness 2030-målen.', 'Stärk civil motståndskraft, infrastrukturskydd och demokratiska skydd.'],
                pl: ['Śledzić oficjalne dane o wydatkach i dostawach, a nie tylko deklaracje polityczne.', 'Priorytetowo traktować wspólne zamówienia, amunicję, obronę powietrzną i mobilność wojskową.', 'Mierzyć produkcję i dostawy względem celów Readiness 2030.', 'Wzmacniać odporność cywilną, ochronę infrastruktury i zabezpieczenia demokratyczne.'],
            ),
            'severity' => CountdownSeverity::Severe,
            'status' => CountdownStatus::Active,
            'target_date' => CarbonImmutable::parse('2030-12-31 23:59:59', 'UTC'),
            'image_path' => $this->shared::IMAGE_PATH,
            'accent_color' => '#2563eb',
            'sort_order' => 2,
            'is_published' => true,
        ];
    }
};
